CREATE TABLE `seller_warehouses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `torod_address_id` VARCHAR(191) NULL,
  `warehouse_code` VARCHAR(191) NOT NULL,
  `warehouse_name` VARCHAR(191) NOT NULL,
  `type` VARCHAR(191) NOT NULL,
  `country_id` INT NULL,
  `region_id` INT NULL,
  `city_id` INT NULL,
  `district_id` INT NULL,
  `address` VARCHAR(191) NULL,
  `locate_address` VARCHAR(191) NULL,
  `latitude` DOUBLE NULL,
  `longitude` DOUBLE NULL,
  `contact_name` VARCHAR(191) NULL,
  `phone_number` VARCHAR(191) NULL,
  `email` VARCHAR(191) NULL,
  `zip_code` VARCHAR(191) NULL,
  `short_address` VARCHAR(191) NULL,
  `is_default` BOOLEAN NOT NULL DEFAULT false,
  `is_return_default` BOOLEAN NOT NULL DEFAULT false,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  INDEX `seller_warehouses_user_id_idx` (`user_id`),
  INDEX `seller_warehouses_warehouse_code_idx` (`warehouse_code`),
  PRIMARY KEY (`id`),
  CONSTRAINT `seller_warehouses_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `User`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
