CREATE TABLE `manual_shipments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `torod_order_id` VARCHAR(191) NULL,
  `tracking_number` VARCHAR(191) NULL,
  `label_url` TEXT NULL,
  `status` VARCHAR(191) NULL,
  `warehouse_code` VARCHAR(191) NOT NULL,
  `warehouse_name` VARCHAR(191) NULL,
  `courier_partner_id` INT NULL,
  `customer_name` VARCHAR(191) NOT NULL,
  `customer_phone` VARCHAR(191) NOT NULL,
  `customer_email` VARCHAR(191) NULL,
  `address` TEXT NOT NULL,
  `country_id` INT NULL,
  `region_id` INT NULL,
  `city_id` INT NULL,
  `district_id` INT NULL,
  `order_total` DECIMAL(10, 2) NOT NULL,
  `weight` FLOAT NOT NULL,
  `no_of_box` INT NOT NULL,
  `payment` VARCHAR(191) NOT NULL,
  `item_description` TEXT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,

  INDEX `manual_shipments_user_id_idx` (`user_id`),
  INDEX `manual_shipments_torod_order_id_idx` (`torod_order_id`),
  PRIMARY KEY (`id`),
  CONSTRAINT `manual_shipments_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `User`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
