CREATE TABLE `vendor_orders` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `order_id` INTEGER NOT NULL,
  `seller_id` INTEGER NOT NULL,
  `status` ENUM('PENDING','PROCESSING','SHIPPED','DELIVERED','CANCELLED','REFUNDED') NOT NULL DEFAULT 'PENDING',
  `shipping_method` VARCHAR(191) NOT NULL DEFAULT 'torod',
  `shipping_company_id` INTEGER NULL,
  `warehouse_code` VARCHAR(191) NULL,
  `shipper_city_id` INTEGER NULL,
  `torod_order_id` VARCHAR(191) NULL,
  `tracking_number` VARCHAR(191) NULL,
  `label_url` VARCHAR(191) NULL,
  `torod_status` VARCHAR(191) NULL,
  `subtotal_amount` DECIMAL(10,2) NOT NULL,
  `discount_amount` DECIMAL(10,2) NOT NULL,
  `shipping_fee` DECIMAL(10,2) NOT NULL,
  `total_amount` DECIMAL(10,2) NOT NULL,
  `platform_fee` DECIMAL(10,2) NOT NULL DEFAULT 0,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `vendor_orders_order_id_idx`(`order_id`),
  INDEX `vendor_orders_seller_id_idx`(`seller_id`),
  CONSTRAINT `vendor_orders_order_id_fkey` FOREIGN KEY (`order_id`) REFERENCES `Order`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `vendor_orders_seller_id_fkey` FOREIGN KEY (`seller_id`) REFERENCES `User`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `vendor_order_items` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `vendor_order_id` INTEGER NOT NULL,
  `order_item_id` INTEGER NOT NULL,
  `product_id` INTEGER NOT NULL,
  `quantity` INTEGER NOT NULL,
  `unit_price` DECIMAL(10,2) NOT NULL,
  `total_price` DECIMAL(10,2) NOT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  INDEX `vendor_order_items_vendor_order_id_idx`(`vendor_order_id`),
  INDEX `vendor_order_items_order_item_id_idx`(`order_item_id`),
  INDEX `vendor_order_items_product_id_idx`(`product_id`),
  CONSTRAINT `vendor_order_items_vendor_order_id_fkey` FOREIGN KEY (`vendor_order_id`) REFERENCES `vendor_orders`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `vendor_order_items_order_item_id_fkey` FOREIGN KEY (`order_item_id`) REFERENCES `order_items`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `vendor_order_items_product_id_fkey` FOREIGN KEY (`product_id`) REFERENCES `Product`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
